#!/usr/bin/env sh

dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

excludefiles=". .. .DS_Store Brewfile .git .gitignore .gitmodules .config .local .config/gtk-3.0 .config/gtk-4.0"
exclude() {
  test "${excludefiles#*$1}" != "$excludefiles"
  return $?
}

for file in .* .local/bin/* .config/* .config/gtk-3.0/* .config/gtk-4.0/*
do
  exclude "$file" && continue

  echo "Linking $file"
 
  # Backup existing files
  if [ -e "$HOME/$file" ] && [ ! -L "$HOME/$file" ]; then
    backup="$file.backup.$(date +%s)"
    mv "$HOME/$file" "$HOME/$backup"
  fi

  # Create symlink
  mkdir -p "$(dirname "$HOME/$file")"
  ln -nfs "$dir/$file" "$HOME/$file"
done

if [ $(uname) = "Darwin" ]; then
  echo "MacOS detected"
  if ! command -v brew &> /dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
  brew bundle --no-lock
fi
