Vagrant.configure(2) do |config|
  config.ssh.forward_agent = true
  config.vm.provision "shell", path: File.join(File.dirname(__FILE__), "provision.sh")
  config.vm.provision "shell", path: File.join(File.dirname(__FILE__), "provision_user.sh"), privileged: false
end
