Vagrant.configure(2) do |config|
  config.vm.synced_folder File.expand_path("~/.dotfiles"), "/home/vagrant/.dotfiles"
  config.vm.provision "shell", path: File.join(File.dirname(__FILE__), "provision.sh")
end
